Finish catalog and basket modules
DmitryLorents/UIKItTemplate pull request #8
Opened 2024-02-17 06:33 UTC by DmitryLorents

2024-02-18 08:46 UTC, Lev-iOS-Dev requested changes

2024-02-18 16:07 UTC, DmitryLorents commented on UIKItTemplate/Extensions/UIFont+Extension.swift
> +//    }
Удалил

2024-02-18 16:13 UTC, DmitryLorents commented on UIKItTemplate/Modules/Basket/Controller/BasketViewController.swift
> +
готово

2024-02-18 16:16 UTC, DmitryLorents commented on UIKItTemplate/Modules/Catalog/Controller/CatalogViewController.swift
> +    }()
Готово

2024-02-18 16:19 UTC, DmitryLorents commented on UIKItTemplate/Modules/Catalog/View/CategoryView.swift
> +
Готово

2024-02-18 16:21 UTC, DmitryLorents commented on UIKItTemplate/Modules/ProductDetailed/Controller/ProductDetailedViewController.swift
>      // MARK: - Visual Components
Так у меня же как раз под ник UI компоненты

2024-02-19 06:42 UTC, Lev-iOS-Dev approved these changes
Плюс

2024-02-19 07:06 UTC, merged